/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;
import model.SinhVienList;
import utilities.Validation;
import utilities.validator;

/**
 *
 * @author PHANMINHTIEN
 */
public class SinhVienView extends javax.swing.JFrame {
    SimpleDateFormat date_form = new SimpleDateFormat("dd/MM/yyyy");
    SinhVienList listSV = new SinhVienList();
//    private DefaultTableModel tbmodel = null;
    String strHinhAnh = null;
    /**
     * Creates new form SinhVienView
     */
    public SinhVienView() {
       
        initComponents();
        fOpen();
    }

//    SinhVienView(FrMain aThis, boolean b) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
    public void  fillDataTABLE(){
        DefaultTableModel tbmodel = (DefaultTableModel)table.getModel();
        tbmodel.setRowCount(0);//clear table
        for(SinhVien sv : listSV.getAllSinhVien()){
          Object rowData[] = new Object[6];
          rowData[0] = sv.getMaSV();
          rowData[1] = sv.getTenSV();
          rowData[2] = date_form.format(sv.getNgaySinh());
          rowData[3] = sv.isGioiTinh()?"NAM" : "NU";
          rowData[4] = sv.getDiaChi();
          rowData[5] = sv.getHinhAnh();
          tbmodel.addRow(rowData);
        }
    }
//    
//    public void loadSinhVienData(){
//        try {
//            listSV.loadFormToFile();
//            listSV.renderToTable(tbmodel);  
//        } catch (IOException ex) {
//            ex.printStackTrace();
//            JOptionPane.showMessageDialog(this, "File Error: " + ex.getMessage());
//        }catch(ClassNotFoundException ex){
//            JOptionPane.showMessageDialog(this, "Not Found Error: " + ex.getMessage());
//        }
//    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lable_MaSinhVien = new javax.swing.JLabel();
        textfield_MaSinhVien = new javax.swing.JTextField();
        lable_HoVaTen = new javax.swing.JLabel();
        textfield_HoVaTen = new javax.swing.JTextField();
        lable_NgaySinh = new javax.swing.JLabel();
        textfield_NgaySinh = new javax.swing.JTextField();
        lable_GioiTinh = new javax.swing.JLabel();
        radiobutton_Nu = new javax.swing.JRadioButton();
        radiobutton_Nam = new javax.swing.JRadioButton();
        lable_DiaChi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_DiaChi = new javax.swing.JTextArea();
        lb_HinhAnh = new javax.swing.JLabel();
        button_Add = new javax.swing.JButton();
        button_Save = new javax.swing.JButton();
        button_Edit = new javax.swing.JButton();
        button_Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        button_ChonAnh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textfield_MaSinhVienTimKiem = new javax.swing.JTextField();
        btn_Search = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItem_Open = new javax.swing.JMenuItem();
        menuItem_Save = new javax.swing.JMenuItem();
        menuItem_Exit = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuItem_AboutMe = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("QUAN LI SINH VIEN");

        lable_MaSinhVien.setText("MA SINH VIEN");

        lable_HoVaTen.setText("HO VA TEN");

        lable_NgaySinh.setText("NGAY SINH");

        lable_GioiTinh.setText("GIOI TINH");

        buttonGroup1.add(radiobutton_Nu);
        radiobutton_Nu.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        radiobutton_Nu.setText("NU");

        buttonGroup1.add(radiobutton_Nam);
        radiobutton_Nam.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        radiobutton_Nam.setSelected(true);
        radiobutton_Nam.setText("NAM");

        lable_DiaChi.setText("DIA CHI");

        textarea_DiaChi.setColumns(20);
        textarea_DiaChi.setRows(5);
        jScrollPane1.setViewportView(textarea_DiaChi);

        lb_HinhAnh.setText("HINH ANH");
        lb_HinhAnh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb_HinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_HinhAnhMouseClicked(evt);
            }
        });

        button_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-add-icon.png"))); // NOI18N
        button_Add.setText("ADD");
        button_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AddActionPerformed(evt);
            }
        });

        button_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-document-save-icon.png"))); // NOI18N
        button_Save.setText("SAVE");
        button_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SaveActionPerformed(evt);
            }
        });

        button_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-document-edit-icon.png"))); // NOI18N
        button_Edit.setText("EDIT");
        button_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_EditActionPerformed(evt);
            }
        });

        button_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Remove-Male-User-icon.png"))); // NOI18N
        button_Delete.setText("DELETE");
        button_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DeleteActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ma SV", "Ten SV", "Ngay Sinh", "Gioi Tinh", "Dia Chi", "Hinh Anh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        button_ChonAnh.setText("Chon Anh");
        button_ChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ChonAnhActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("MA SINH VIEN");

        btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search-icon.png"))); // NOI18N
        btn_Search.setText("Search");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(textfield_MaSinhVienTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textfield_MaSinhVienTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        menuFile.setText("File");

        menuItem_Open.setText("Open");
        menuItem_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_OpenActionPerformed(evt);
            }
        });
        menuFile.add(menuItem_Open);

        menuItem_Save.setText("Save");
        menuItem_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_SaveActionPerformed(evt);
            }
        });
        menuFile.add(menuItem_Save);

        menuItem_Exit.setText("Exit");
        menuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItem_Exit);

        jMenuBar1.add(menuFile);

        menuAbout.setText("About");

        menuItem_AboutMe.setText("About Me");
        menuItem_AboutMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_AboutMeActionPerformed(evt);
            }
        });
        menuAbout.add(menuItem_AboutMe);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lable_MaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lable_HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lable_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lable_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lable_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfield_MaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfield_HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfield_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radiobutton_Nam)
                                        .addGap(9, 9, 9)
                                        .addComponent(radiobutton_Nu)))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_HinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button_ChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_HinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(button_ChonAnh))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textfield_MaSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textfield_HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lable_HoVaTen))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textfield_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lable_NgaySinh)))
                            .addComponent(lable_MaSinhVien))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lable_DiaChi))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radiobutton_Nam)
                                .addComponent(lable_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(radiobutton_Nu))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(button_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_HinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_HinhAnhMouseClicked
       
    }//GEN-LAST:event_lb_HinhAnhMouseClicked
    public void reset(){
        textfield_MaSinhVien.setText("");
        textfield_HoVaTen.setText("");
        textfield_NgaySinh.setText("");
        textarea_DiaChi.setText("");
        radiobutton_Nam.isSelected();
        lb_HinhAnh.setText("HINH ANH");
        lb_HinhAnh.setIcon(null);
        strHinhAnh = null;
    }
    private void button_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AddActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_button_AddActionPerformed
    
//    public boolean validateForm(){
//       if(textfield_MaSinhVien.getText().isEmpty() || textfield_HoVaTen.getText().isEmpty()){
//           return false;
//       } 
//       return true;
//    }
    public boolean validateForm(){
        if(Validation.isEmpty(textfield_MaSinhVien, "Ma Sinh Vien khong duoc trong!")){
            return false;
        }
        if(Validation.isEmpty(textfield_HoVaTen, "Ten Sinh Vien khong duoc trong!")){
            return false;
        }
        if(Validation.isEmpty(textfield_NgaySinh, "Ngay sinh khong duoc de trong!")){
            return false;
        }
        if(Validation.isDate(textfield_NgaySinh, "Ngay sinh sai dinh dang")){
            
        }
        if(Validation.isEmpty(textarea_DiaChi, "Dia chi khong duoc de trong!")){
            return false;
        }
        
        return true;
    }
    
    public SinhVien getDuLieu() throws ParseException{
        SinhVien sv = new SinhVien();
        sv.setMaSV(textfield_MaSinhVien.getText());
        sv.setTenSV(textfield_HoVaTen.getText());
        sv.setNgaySinh(date_form.parse(textfield_NgaySinh.getText()));
//        sv.setGioiTinh(rootPaneCheckingEnabled);
        boolean gt = false; // Xet mac dinh gioi tinh ban dau la Nu
        if(radiobutton_Nam.isSelected()){
            gt = true;//Nam
        }
        sv.setGioiTinh(gt);
        sv.setDiaChi(textarea_DiaChi.getText());
        if(strHinhAnh == null){
            sv.setHinhAnh("NO AVATAR");
        }else{
            sv.setHinhAnh(strHinhAnh);
        }
        return sv;
    }
    
    
    private void button_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SaveActionPerformed
        // TODO add your handling code here:
           if(!validateForm()){
               return;
           }
          try {
             SinhVien sv = getDuLieu();
           if (listSV.getSinhVienByID(sv.getMaSV()) != null) {
               JOptionPane.showMessageDialog(this, "ID of student exist!");
               return;
           }
           else if(listSV.add(sv)>0){
               JOptionPane.showMessageDialog(this, "Luu Thanh Cong");
               fillDataTABLE();
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       
    }//GEN-LAST:event_button_SaveActionPerformed
    // setmodel() dung de do nguoc du lieu len form
    public void setModel(SinhVien sv){
        textfield_MaSinhVien.setText(sv.getMaSV());
        textfield_HoVaTen.setText(sv.getTenSV());
        if(sv.isGioiTinh()){
            radiobutton_Nam.setSelected(true);
        }else{
            radiobutton_Nu.setSelected(true);
        }
        //load Hinh anh
        lb_HinhAnh.setText("");
        if(sv.getHinhAnh().equalsIgnoreCase("no avatar")){
            lb_HinhAnh.setText("NO AVATAR");
            lb_HinhAnh.setIcon(null);
        }else{
            lb_HinhAnh.setText("");
            ImageIcon imgaIcon = new ImageIcon(getClass().getResource("/images/"+sv.getHinhAnh()));
            Image img = imgaIcon.getImage();
            img.getScaledInstance(lb_HinhAnh.getWidth(), lb_HinhAnh.getHeight(), 0);       
            lb_HinhAnh.setIcon(imgaIcon);
        }
        textfield_NgaySinh.setText(date_form.format(sv.getNgaySinh()));
        textarea_DiaChi.setText(sv.getDiaChi());
    }
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int id = table.rowAtPoint(evt.getPoint());
        String maSV = table.getValueAt(id, 0).toString();//Tim Ma Sv roi tu Ma Sv lay dc lai thong tin cua sinh vien da nhap
        SinhVien sv = listSV.getSinhVienByID(maSV);
        setModel(sv);
    }//GEN-LAST:event_tableMouseClicked
    
//    public ImageIcon ResizeImage(String ImagePath){
//            ImageIcon myImage = new ImageIcon(ImagePath);
//            Image img = myImage.getImage();
//            Image newImg = img.getScaledInstance(lb_HinhAnh.getWidth(), lb_HinhAnh.getHeight(), Image.SCALE_SMOOTH);
//            ImageIcon image = new ImageIcon(newImg);
//            return image;
//
//    }
    private void button_ChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ChonAnhActionPerformed
        try {
            // TODO add your handling code here:
            JFileChooser jfc = new JFileChooser("D:\\GUI Java\\ASMQUANLYSINHVIEN\\src\\images");
            jfc.showOpenDialog(null);
            File file = jfc.getSelectedFile();
            Image img = ImageIO.read(file);
            strHinhAnh = file.getName();
            lb_HinhAnh.setText("");
            int width = lb_HinhAnh.getWidth();
            int height = lb_HinhAnh.getHeight();
            lb_HinhAnh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
           
        } catch (IOException ex) {
                System.out.println("Error: " + ex.toString());
            }
        


       
    }//GEN-LAST:event_button_ChonAnhActionPerformed

    private void writeFile(){
         FileOutputStream fos = null;
         ObjectOutputStream oos = null;
        try{
        fos = new FileOutputStream("data.dat");
        oos = new ObjectOutputStream(fos);
        oos.writeObject(listSV);
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            try{
                oos.close();
                fos.close();
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }
    
    private void readFile(){
         FileInputStream fis = null;
         ObjectInputStream ois = null;
        try{
        fis = new FileInputStream("data.dat");
        ois = new ObjectInputStream(fis);
        listSV = (SinhVienList)ois.readObject();
        }catch(FileNotFoundException e){
            
        
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            try{
                if(ois!=null && fis!=null){
                    ois.close();
                    fis.close();
                }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }
      
    private void fOpen(){
//        curIdx = -1;
//        list.clear();
//        list.add(new SinhVien("1", "Alo", new Date(), true, "danang", "NO AVATAR"));
//        list.add(new SinhVien("2", "Alo", new Date(), false, "quang binh", "NO AVATAR"));
//        list.add(new SinhVien("3", "Alo", new Date(), true, "nghe an", "NO AVATAR"));
        readFile();
        fillDataTABLE();
        
        
    }
    
    private void button_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_EditActionPerformed
        // TODO add your handling code here:
       
        
            try {
                StringBuilder sb = new StringBuilder();
                validator.checkName(textfield_HoVaTen, sb);
               
                if (sb.length() >0) {
                   JOptionPane.showMessageDialog(this, sb.toString(),"Loi",JOptionPane.ERROR_MESSAGE);
                }
                else {
                     SinhVien sv = getDuLieu();
                    if(listSV.updateSinhVienByID(sv) > 0) {
                    JOptionPane.showMessageDialog(this, "Cap nhat thanh cong");
                    fillDataTABLE();
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(SinhVienView.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }//GEN-LAST:event_button_EditActionPerformed

    private void button_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DeleteActionPerformed
        // TODO add your handling code here:
        
            if(listSV.deleteSinhVienByID(textfield_MaSinhVien.getText())>0){
                JOptionPane.showMessageDialog(this, "Xoa thanh cong");
                fillDataTABLE();
            }else{
                JOptionPane.showMessageDialog(this, "Khong tim thay sinh vien de xoa");
            }
        
    }//GEN-LAST:event_button_DeleteActionPerformed
   
    private void menuItem_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_OpenActionPerformed
        // TODO add your handling code here:
        fOpen();
    }//GEN-LAST:event_menuItem_OpenActionPerformed
    
    private void menuItem_AboutMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_AboutMeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Phan mem Quan Ly Sinh Vien 4.0");
    }//GEN-LAST:event_menuItem_AboutMeActionPerformed

    private void menuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ExitActionPerformed
        // TODO add your handling code here:
        int luaChon = JOptionPane.showConfirmDialog(
			    this,
			    "Bạn có muốn thoải khỏi chương trình?",
			    "Exit",
			    JOptionPane.YES_NO_OPTION);
		if (luaChon == JOptionPane.YES_OPTION) {
                        writeFile();
			System.exit(0);
		}
    }//GEN-LAST:event_menuItem_ExitActionPerformed
   
    private void menuItem_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_SaveActionPerformed
        // TODO add your handling code here:
        writeFile();
        JOptionPane.showMessageDialog(this, "Luu file thanh cong");
    }//GEN-LAST:event_menuItem_SaveActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        // TODO add your handling code here:
            StringBuilder sb = new StringBuilder();
            validator.checkId(textfield_MaSinhVienTimKiem, sb); 
            if (sb.length() >0) {
               JOptionPane.showMessageDialog(this, sb.toString(),"Loi",JOptionPane.ERROR_MESSAGE);
            }else{
                SinhVien sv = listSV.getSinhVienByID(textfield_MaSinhVienTimKiem.getText());
                if(sv != null){
                    SinhVien st = listSV.getOneStudentByMaSV(sv.getMaSV());
                    if(st!= null){
                        setModel(st);
                    } else{
                    textfield_MaSinhVien.setText("");
                    textfield_HoVaTen.setText("");
                    textfield_NgaySinh.setText("");
                    radiobutton_Nu.isSelected();
                    textarea_DiaChi.setText("");
                    lb_HinhAnh.setText(strHinhAnh);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Ma sinh vien ko ton tai");
                }
        }
    }//GEN-LAST:event_btn_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Search;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_Add;
    private javax.swing.JButton button_ChonAnh;
    private javax.swing.JButton button_Delete;
    private javax.swing.JButton button_Edit;
    private javax.swing.JButton button_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lable_DiaChi;
    private javax.swing.JLabel lable_GioiTinh;
    private javax.swing.JLabel lable_HoVaTen;
    private javax.swing.JLabel lable_MaSinhVien;
    private javax.swing.JLabel lable_NgaySinh;
    private javax.swing.JLabel lb_HinhAnh;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItem_AboutMe;
    private javax.swing.JMenuItem menuItem_Exit;
    private javax.swing.JMenuItem menuItem_Open;
    private javax.swing.JMenuItem menuItem_Save;
    private javax.swing.JRadioButton radiobutton_Nam;
    private javax.swing.JRadioButton radiobutton_Nu;
    private javax.swing.JTable table;
    private javax.swing.JTextArea textarea_DiaChi;
    private javax.swing.JTextField textfield_HoVaTen;
    private javax.swing.JTextField textfield_MaSinhVien;
    private javax.swing.JTextField textfield_MaSinhVienTimKiem;
    private javax.swing.JTextField textfield_NgaySinh;
    // End of variables declaration//GEN-END:variables

    
}
